### PR TITLE
feat: add simple aggregated stats

### LINKED ISSUE #142: Suggestion: add aggregated statistics
Currently, only per vault stats are displayed. The community currently doesn't have a single source of truth for useful aggregated stats like TVL. Stats on external sources (e.g. DeFi pulse) are not 100% accurate. Until the yearn API is improved to incorporate aggregated stats, some simple client-side calcs maybe the way to go:

- Total Holdings
- Vault Holdings 
- Strategy Holdings (assume this is money that's deployed into the strategies?)
- Growth Run Rate (e.g. estimated annual yield in % and $ for active strategies)

image

### PR DESCRIPTION
**Pull request by wirjo**
Closes #142

### CODE REVIEW

**Review by x48-crypto — APPROVED** [review]
Looks good, tested locally as well!

**Comment by WrongNebula** [comment]
Could correct copy a bit:

Total Holdings -> Total holdings
(Or: Total value locked? Or: Total assets under management (AUM))

Vault Holdings -> Vaults holdings

Strategy Holdings -> Strategies holdings

Growth Run Rate -> Growth run rate
(not sure I understand that metric, what's the tooltip saying?)

**Comment by wirjo** [comment]
@WrongNebula It's the annual yield in % and $ term based on 1 month sample. Any thoughts on the copy? "Growth Run Rate" is probably not 100% right. Maybe "Annual Yield (1 mo)" ?

**Comment by WrongNebula** [comment]
@wirjo 

1. Yes let's use the most commonly known and used term, Total value locked (TVL)

2. Good tooltip wording. You could add `Total holdings deployed into vault strategies. Not including holdings deployed to other protocols.`

3. Is that an average of all strategies since inception? I'll Discord you for more details, we need to get this copy right and understandable by the largest amount of users.

**Comment by wirjo** [comment]
No worries, I have made initial amendments based on your feedback:

* **Total Value Locked (TVL):** (No tooltip)
* **Vault Holding:** `Total assets held in vaults, excluding assets that are deployed into other protocols`
* **Strategy Holdings:** `Total assets deployed to other protocols as part of vault strategies`
* **Annual Yield:** `Average annual yield (unstable) based on 1 month sampled period, across active vaults`

**Comments**

* I think "Holdings" are already pluralised so we should not pluralise "vaults" or "strategies". The tooltip and the fact that they are big numbers on top of the page should be sufficient to communicate that it is across all vaults.

* With **Annual Yield**, it is based on the 1-month sample. My understanding is that it is probably the best predictor of future yield rather than inception, which may be over-inflated. 

* The calculation is across all **active** vaults, so it sums up all the $ yield across all active vaults and then divides it by the active $ TVL. In the screenshot, the $ yield across all active vaults is the `$35.9m` figure. 

Feel free to ping me on the #frontend channel on Discord.

image

**Pull request merged**
